apiVersion: apps/v1
kind: Deployment
metadata:
  name: shifts-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
        app: shifts-deployment
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: shifts-deployment
        tier: frontend
    spec:
      containers:
      - name: nginx-demo
        image: nginx
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
        ports:
        - containerPort: 80